package edu.uor.remco

/** Tiny two-language string table (Kurdish Sorani / English), switchable in-app. */
object L {
    var ku: Boolean = true

    private val en = mapOf(
        "connect" to "Connect",
        "disconnect" to "Disconnect",
        "notConnected" to "Not connected",
        "connecting" to "Connecting to %s…",
        "connectedTo" to "Connected: %s",
        "reconnecting" to "Connection lost — retrying…",
        "failed" to "Could not connect. Is UOR-RC open on the PC?",
        "choosePc" to "Choose your computer",
        "noPaired" to "No computer found. Put the phone and the computer on the same Wi-Fi/hotspot with UOR-RC open, or pair them in Bluetooth settings.",
        "btOff" to "Bluetooth is off. Turn it on and try again.",
        "noBt" to "This phone has no Bluetooth.",
        "needPerm" to "Bluetooth permission is needed to talk to the computer.",
        "openBtSettings" to "Bluetooth settings",
        "cancel" to "Cancel",
        "ok" to "OK",
        "noPpt" to "PowerPoint is not open on the PC — buttons send arrow keys",
        "pptOpen" to "PowerPoint open · not presenting",
        "slide" to "Slide",
        "current" to "Now",
        "nextSlide" to "Next",
        "end" to "End",
        "anim" to "Animation %d / %d",
        "noAnim" to "No more animations on this slide",
        "next" to "NEXT ▶",
        "prev" to "◀",
        "mouse" to "🖱 Mouse",
        "laser" to "🔴 Laser",
        "pen" to "✏️ Pen",
        "highlight" to "🖍 Highlight",
        "eraser" to "🧽 Eraser",
        "clear" to "🗑 Clear",
        "notes" to "📝 Notes",
        "noNotes" to "(No speaker notes on this slide)",
        "start" to "▶ Start",
        "startCur" to "▶ From here",
        "endShow" to "■ End",
        "black" to "⬛ Black",
        "white" to "⬜ White",
        "zoomIn" to "🔍+",
        "zoomOut" to "🔍−",
        "slides" to "☰ Slides",
        "settings" to "⚙",
        "goTo" to "Go to slide",
        "timer" to "Timer",
        "minutes" to "Minutes",
        "startTimer" to "Start",
        "pauseTimer" to "Pause",
        "resetTimer" to "Reset",
        "timeUp" to "Time is up!",
        "hintMouse" to "Drag = move · Tap = click · 2-finger tap = right-click · 2-finger drag = scroll · Hold then drag = drag",
        "hintLaser" to "Touch inside the frame — the laser appears on the same spot of the slide · 2 fingers = zoom",
        "hintPen" to "Draw inside the frame — ink appears on the slide in PowerPoint",
        "hintEraser" to "Rub over ink inside the frame to erase it",
        "volKeys" to "Volume keys change slides (also when the screen is locked, while UOR-RC is open)",
        "showSlideOnPad" to "Show slide inside the pad (laser / pen)",
        "sensitivity" to "Touchpad speed",
        "vibrate" to "Vibrate on tap",
        "settingsTitle" to "Settings",
        "viaWifi" to "Wi-Fi",
        "gallery" to "📸 Group photos",
        "galGrid" to "⊞ All",
        "galOne" to "🔍 One",
        "galClear" to "🗑 Clear",
        "galClearAsk" to "Remove all the photos taken in this lesson?",
        "quizTime" to "⏱ Time limit for this question",
        "quizNoTime" to "No limit",
        "quietPhone" to "Turn the phone almost silent while its sound goes to the PC",
        "speaker" to "🔈 Sound only on PC",
        "speakerOn" to "🔈 Sound on PC ✓",
        "speakerConnecting" to "Connecting the PC as the phone's Bluetooth speaker…",
        "speakerDone" to "🔈 The phone's sound now plays only on the PC",
        "speakerFail" to "The PC could not become the phone's speaker. Make sure the phone is PAIRED with this PC in Bluetooth settings, Bluetooth is on on both, and the PC runs Windows 10 (2004) or newer.",
        "lens" to "🔎 Lens",
        "hintLens" to "Touch and move — a round magnifier follows your finger on the projector",
        "magnify" to "Magnify",
        "camera" to "📷 Camera",
        "board" to "🧑‍🏫 Whiteboard",
        "docs" to "📑 PDF / Word",
        "quiz" to "🗳️ Quiz",
        "picker" to "🎲 Picker",
        "pageOf" to "Page %d / %d",
        "newPage" to "➕ New page",
        "bgWhite" to "⬜ White",
        "bgGrid" to "▦ Grid",
        "bgBlack" to "⬛ Black",
        "bgGreen" to "🟩 Green",
        "boardSaved" to "Whiteboard saved on the PC (%d pages) — Downloads › UOR-RC",
        "docPreparing" to "Opening it on the projector…",
        "quizTitle" to "🗳️ Live quiz / poll",
        "quizQuick" to "⚡ Quick question (A, B, C…)",
        "quizWordsHint" to "Optional: a few words next to each letter",
        "quizNewQuiz" to "➕ New quiz",
        "quizPlay" to "▶ Play",
        "quizEdit" to "✏️ Edit",
        "quizDelete" to "🗑 Delete",
        "quizDeleteAsk" to "Delete the quiz \"%s\"?",
        "quizName" to "Quiz name (e.g. Morphology – week 4)",
        "quizUntitled" to "My quiz",
        "quizAddQ" to "➕ Add question",
        "quizQuestion" to "Question",
        "quizOptionsHint" to "Answers — write them, and tick the correct one",
        "quizAnswerHint" to "Answer",
        "quizAnswerOpt" to "Answer (optional)",
        "quizNextQ" to "▶ Next question",
        "quizScores" to "🏆 Scores",
        "quizReset" to "♻️ Reset scores",
        "quizResetAsk" to "Set everybody's score back to zero?",
        "pickWheel" to "🎡 Spin a wheel instead of showing names",
        "pickWheelShort" to "🎡 Wheel",
        "quizQuestionHint" to "Question (optional)",
        "quizHowMany" to "Answers",
        "quizNote" to "Students type their name, answer, and get points for speed (like Kahoot). They join the same Wi-Fi as the computer (the laptop hotspot fits up to 8 phones — for a big class use the classroom Wi-Fi), then scan the code on the projector. No app needed.",
        "quizStart" to "▶ Start",
        "quizAnswers" to "👥 %d answers",
        "quizShowResults" to "📊 Show results",
        "quizCorrect" to "✓ Correct:",
        "quizNew" to "🔁 New question",
        "pickTitle" to "🎲 Random student picker",
        "pickNamesHint" to "Names, one per line — or type 1-30 for numbers",
        "pickNoRepeat" to "Don't pick the same student twice (until everyone had a turn)",
        "pickBtn" to "🎲 Pick",
        "pickAgain" to "🎲 Pick again",
        "pickLists" to "📋 Class lists",
        "pickNewList" to "➕ New list",
        "pickListName" to "List name (e.g. Stage 2 – Group A)",
        "pickDefaultList" to "My class",
        "pickEmpty" to "Add some names first.",
        "pickLeft" to "%d left",
        "mutePhone" to "🔇 Mute phone",
        "unmutePhone" to "🔈 Phone sound on",
        "muteKillsPc" to "On this phone, muting also silences the sound sent to the computer, so UOR-RC turned the phone sound back on.\n\nTip: for videos from your gallery use 🖼 Photos & videos — they play on the computer only.",
        "scan" to "📷 Scan",
        "scanQr" to "📷 Scan the QR code in UOR-RC on the PC",
        "scanPrompt" to "Point at the QR code in UOR-RC on the computer",
        "scanBad" to "That isn't a UOR-RC QR code. Scan the one shown in UOR-RC on the computer.",
        "joining" to "Joining %s…",
        "joinFailed" to "Couldn't join %s. Join it in the phone's Wi-Fi settings, then UOR-RC connects by itself.",
        "cameraPerm" to "The camera is needed to scan the QR code.",
        "mute" to "🔇",
        "unmute" to "🔈",
        "mediaAgain" to "▶ Back to the same photos & videos",
        "mediaNew" to "➕ Choose new ones",
        "media" to "🖼 Photos & videos",
        "mediaTitle" to "Show on the projector",
        "mediaWhat" to "Show these full-screen on the projector, or save them on the computer?",
        "mediaShow" to "🖼 Show full-screen",
        "mediaSave" to "💾 Save on PC",
        "mediaBt" to "These files are %d MB. Over Bluetooth that takes a while — Wi-Fi is much faster. Continue?",
        "mediaPreparing" to "Preparing on the projector… %d%%",
        "mediaClose" to "✕ Close",
        "mediaFill" to "⛶ Fill",
        "mediaRotate" to "🔄",
        "mediaPhoto" to "Photo %d / %d",
        "mediaVideo" to "Video %d / %d",
        "yes" to "Yes",
        "files" to "📁 Files",
        "sendToPc" to "📤 Send files to the computer",
        "whereFiles" to "Files from the computer are saved in Downloads › UOR-RC.\nOn the computer: Downloads\\UOR-RC. You can also Share → UOR-RC from any app, or drag files onto the UOR-RC window on the PC.",
        "sending" to "→ PC: %s  %d%%",
        "receiving" to "← PC: %s  %d%%",
        "received" to "Received from the computer: %s",
        "open" to "Open",
        "failedFile" to "Transfer failed: %s",
        "sendLater" to "Will send when the computer is connected.",
        "rotate" to "🔄 Rotate %d°",
        "fill" to "⛶ Fill screen",
        "fit" to "⛶ Fit",
        "sound" to "🔊 Sound",
        "soundOff" to "🔇 Sound",
        "soundNeeds10" to "Sending sound needs Android 10 or newer.",
        "soundPerm" to "Android calls this \"record audio\" — UOR-RC only takes what apps play, not the microphone.",
        "phoneOnPc" to "📱 Phone screen on PC",
        "volSwap" to "Volume UP = next slide (normally volume DOWN = next)",
        "leftBtn" to "Left click",
        "rightBtn" to "Right click",
        "autoKb" to "Open the keyboard when I click in a text box on the PC",
        "hideKb" to "⌄ Hide",
        "copy" to "Copy",
        "paste" to "Paste",
        "undo" to "Undo",
        "selAll" to "Select all",
        "phoneHotspot" to "📱 Make a hotspot on this phone",
        "hsNeedPerm" to "Android needs this permission to create the hotspot.",
        "hsOn" to "Hotspot on this phone is ON",
        "hsInfo" to "Name: %s\nPassword: %s",
        "hsAuto" to "UOR-RC is joining the laptop to it automatically (via Bluetooth)… then it switches to Wi-Fi.",
        "hsManual" to "On the laptop, open the Wi-Fi list and join this network. UOR-RC then connects by itself.",
        "hsOff" to "Turn hotspot off",
        "hsFail" to "The phone could not start the hotspot (%s). If your normal hotspot is on, turn it off — or just connect the laptop to it. On older Android, turn Location on.",
        "desktop" to "🖥 Desktop",
        "backShow" to "▶ Back to PowerPoint",
        "seeScreen" to "📺 See the screen",
        "hintMirror" to "Tap exactly what you want to click · hold = right-click · drag = drag · 2 fingers = zoom the picture",
        "viaBt" to "Bluetooth",
        "pinTitle" to "Wi-Fi PIN",
        "pinMsg" to "Type the 4-digit PIN shown in UOR-RC on the computer.",
        "pinFound" to "UOR-RC found %s on Wi-Fi too. Enter its PIN for the faster Wi-Fi connection.",
        "pinWrong" to "Wi-Fi didn't connect. Check the PIN shown in UOR-RC on the computer.",
        "connMode" to "Connection",
        "modeAuto" to "Automatic — Wi-Fi first, Bluetooth as backup (recommended)",
        "modeWifi" to "Wi-Fi only",
        "modeBt" to "Bluetooth only",
        "thisPhone" to "This phone's address: %s",
        "searching" to "Looking for the computer…",
        "btList" to "Bluetooth devices…",
        "spotlight" to "🔦 Spotlight",
        "zoom" to "🔍 Zoom",
        "number" to "🔢 Number",
        "text" to "📍 Text",
        "size" to "Size",
        "colorL" to "Color",
        "write" to "✍️ Write",
        "writeHint" to "Type something to show…",
        "confettiOn" to "🎊 Confetti on",
        "confettiOff" to "🎊 Confetti off",
        "colored" to "🫟 Colored",
        "reset" to "Reset",
        "pin" to "📍 Pin",
        "plain" to "💬 Plain",
        "box" to "🔲 Box",
        "fontColor" to "Font color",
        "background" to "Background",
        "noBg" to "No bg",
        "addLabel" to "Add label",
        "editLabel" to "Edit label",
        "labelHint" to "Type your label…",
        "save" to "Save",
        "delete" to "Delete",
        "countdown" to "⌛ Countdown",
        "stopwatch" to "⏱ Stopwatch",
        "onProjector" to "Show on the projector",
        "silent" to "Silent (no vibration)",
        "showPreviews" to "Show slide previews",
        "hintSpot" to "Touch and move — a spotlight follows your finger · 2 fingers = zoom",
        "hintZoom" to "Like photos on your phone: pinch to zoom where your fingers are · drag to move · double-tap to zoom in / out",
        "hintNumber" to "Tap to drop the next number (it appears just above your finger) · tap a number to remove it",
        "hintText" to "Tap where the label should go · tap a label to edit or delete it"
    )

    private val ckb = mapOf(
        "connect" to "پەیوەستبوون",
        "disconnect" to "پچڕاندن",
        "notConnected" to "پەیوەست نییە",
        "connecting" to "پەیوەست دەبێت بە %s…",
        "connectedTo" to "پەیوەستە: %s",
        "reconnecting" to "پەیوەندی پچڕا — دووبارە هەوڵ دەدرێتەوە…",
        "failed" to "پەیوەست نەبوو. ئایا UOR-RC لەسەر کۆمپیوتەرەکە کراوەتەوە؟",
        "choosePc" to "کۆمپیوتەرەکەت هەڵبژێرە",
        "noPaired" to "هیچ کۆمپیوتەرێک نەدۆزرایەوە. مۆبایل و کۆمپیوتەرەکە بخە سەر هەمان وای‌فای/هۆتسپۆت و UOR-RC بکەرەوە، یان لە ڕێکخستنەکانی بلوتوس جووتیان بکە.",
        "btOff" to "بلوتوس کوژاوەتەوە. هەڵیبکە و دووبارە هەوڵ بدەرەوە.",
        "noBt" to "ئەم مۆبایلە بلوتوسی نییە.",
        "needPerm" to "بۆ قسەکردن لەگەڵ کۆمپیوتەرەکە ڕێگەپێدانی بلوتوس پێویستە.",
        "openBtSettings" to "ڕێکخستنی بلوتوس",
        "cancel" to "پاشگەزبوونەوە",
        "ok" to "باشە",
        "noPpt" to "پاوەرپۆینت لەسەر کۆمپیوتەرەکە کراوە نییە — دوگمەکان تیرەکانی کیبۆرد دەنێرن",
        "pptOpen" to "پاوەرپۆینت کراوەیە · پیشاندان دەستی پێنەکردووە",
        "slide" to "سلاید",
        "current" to "ئێستا",
        "nextSlide" to "دواتر",
        "end" to "کۆتایی",
        "anim" to "ئەنیمەیشن %d / %d",
        "noAnim" to "ئەنیمەیشنی تر لەم سلایدەدا نییە",
        "next" to "دواتر ▶",
        "prev" to "◀",
        "mouse" to "🖱 ماوس",
        "laser" to "🔴 لێزەر",
        "pen" to "✏️ پێنووس",
        "highlight" to "🖍 هایلایت",
        "eraser" to "🧽 پاکەرەوە",
        "clear" to "🗑 سڕینەوە",
        "notes" to "📝 تێبینی",
        "noNotes" to "(ئەم سلایدە تێبینی نییە)",
        "start" to "▶ دەستپێکردن",
        "startCur" to "▶ لێرەوە",
        "endShow" to "■ کۆتایی",
        "black" to "⬛ ڕەشکردنەوە",
        "white" to "⬜ سپیکردنەوە",
        "zoomIn" to "🔍+",
        "zoomOut" to "🔍−",
        "slides" to "☰ سلایدەکان",
        "settings" to "⚙",
        "goTo" to "بڕۆ بۆ سلاید",
        "timer" to "کات",
        "minutes" to "خولەک",
        "startTimer" to "دەستپێکردن",
        "pauseTimer" to "وەستاندن",
        "resetTimer" to "سفرکردنەوە",
        "timeUp" to "کات تەواو بوو!",
        "hintMouse" to "ڕاکێشان = جووڵاندن · لێدان = کلیک · لێدانی دوو پەنجە = کلیکی ڕاست · ڕاکێشانی دوو پەنجە = سکڕۆڵ",
        "hintLaser" to "لە ناو چوارچێوەکەدا دەست لێبدە — لێزەرەکە لە هەمان شوێنی سلایدەکە دەردەکەوێت",
        "hintPen" to "لە ناو چوارچێوەکەدا بکێشە — لەسەر سلایدەکە لە پاوەرپۆینت دەردەکەوێت",
        "hintEraser" to "بەسەر کێشراوەکاندا بیجووڵێنە بۆ سڕینەوەیان",
        "volKeys" to "دوگمەکانی دەنگ سلاید دەگۆڕن (تەنانەت کاتێک شاشە داخراوە، ئەگەر UOR-RC کراوە بێت)",
        "showSlideOnPad" to "سلاید لە ناو پادەکەدا پیشان بدە (لێزەر / پێنووس)",
        "sensitivity" to "خێرایی تاچپاد",
        "vibrate" to "لەرینەوە لە کاتی لێدان",
        "settingsTitle" to "ڕێکخستنەکان",
        "viaWifi" to "وای‌فای",
        "gallery" to "📸 وێنەی گرووپەکان",
        "galGrid" to "⊞ هەموو",
        "galOne" to "🔍 یەکە",
        "galClear" to "🗑 سڕینەوە",
        "galClearAsk" to "هەموو وێنەکانی ئەم وانەیە لاببرێن؟",
        "quizTime" to "⏱ سنووری کات بۆ ئەم پرسیارە",
        "quizNoTime" to "بێ سنوور",
        "quietPhone" to "کاتێک دەنگ بۆ کۆمپیوتەر دەچێت، مۆبایل زۆر نزم بکەرەوە",
        "speaker" to "🔈 دەنگ تەنها لەسەر کۆمپیوتەر",
        "speakerOn" to "🔈 دەنگ لەسەر کۆمپیوتەر ✓",
        "speakerConnecting" to "کۆمپیوتەرەکە دەکرێتە سپیکەری بلوتوسی مۆبایلەکە…",
        "speakerDone" to "🔈 دەنگی مۆبایلەکە ئێستا تەنها لەسەر کۆمپیوتەر لێدەدرێت",
        "speakerFail" to "کۆمپیوتەرەکە نەیتوانی ببێتە سپیکەری مۆبایلەکە. دڵنیابە کە مۆبایلەکە لە ڕێکخستنی بلوتوسدا لەگەڵ ئەم کۆمپیوتەرە جووتکراوە، بلوتوس لە هەردووکیان هەڵکراوە، و کۆمپیوتەرەکە ویندۆز ١٠ (2004) یان نوێتری هەیە.",
        "lens" to "🔎 گەورەبین",
        "hintLens" to "دەست لێبدە و بیجووڵێنە — گەورەبینێکی بازنەیی بە دوای پەنجەتدا دێت لەسەر پرۆجێکتەر",
        "magnify" to "گەورەکردن",
        "camera" to "📷 کامێرا",
        "board" to "🧑‍🏫 تەختەی سپی",
        "docs" to "📑 PDF / Word",
        "quiz" to "🗳️ تاقیکردنەوە",
        "picker" to "🎲 هەڵبژاردن",
        "pageOf" to "لاپەڕە %d / %d",
        "newPage" to "➕ لاپەڕەی نوێ",
        "bgWhite" to "⬜ سپی",
        "bgGrid" to "▦ خانەخانە",
        "bgBlack" to "⬛ ڕەش",
        "bgGreen" to "🟩 سەوز",
        "boardSaved" to "تەختەکە لەسەر کۆمپیوتەر پاشەکەوت کرا (%d لاپەڕە) — Downloads › UOR-RC",
        "docPreparing" to "لەسەر پرۆجێکتەر دەکرێتەوە…",
        "quizTitle" to "🗳️ تاقیکردنەوە / ڕاپرسیی ڕاستەوخۆ",
        "quizQuick" to "⚡ پرسیاری خێرا (A, B, C…)",
        "quizWordsHint" to "ئارەزوومەندانە: چەند وشەیەک لە تەنیشت هەر پیتێک",
        "quizNewQuiz" to "➕ تاقیکردنەوەی نوێ",
        "quizPlay" to "▶ دەستپێکردن",
        "quizEdit" to "✏️ دەستکاری",
        "quizDelete" to "🗑 سڕینەوە",
        "quizDeleteAsk" to "تاقیکردنەوەی \"%s\" بسڕدرێتەوە؟",
        "quizName" to "ناوی تاقیکردنەوە (بۆ نموونە مۆرفۆلۆجی – هەفتەی ٤)",
        "quizUntitled" to "تاقیکردنەوەکەم",
        "quizAddQ" to "➕ زیادکردنی پرسیار",
        "quizQuestion" to "پرسیار",
        "quizOptionsHint" to "وەڵامەکان — بینووسە و وەڵامی ڕاست دیاری بکە",
        "quizAnswerHint" to "وەڵام",
        "quizAnswerOpt" to "وەڵام (ئارەزوومەندانە)",
        "quizNextQ" to "▶ پرسیاری دواتر",
        "quizScores" to "🏆 خاڵەکان",
        "quizReset" to "♻️ سفرکردنەوەی خاڵ",
        "quizResetAsk" to "خاڵی هەمووان بگەڕێندرێتەوە بۆ سفر؟",
        "pickWheel" to "🎡 لە جیاتی ناوەکان چەرخە بسووڕێنە",
        "pickWheelShort" to "🎡 چەرخە",
        "quizQuestionHint" to "پرسیار (ئارەزوومەندانە)",
        "quizHowMany" to "وەڵامەکان",
        "quizNote" to "قوتابیان ناوی خۆیان دەنووسن، وەڵام دەدەنەوە و بەپێی خێرایی خاڵ وەردەگرن (وەک Kahoot). بە هەمان وای‌فای کۆمپیوتەرەکەوە پەیوەست دەبن (هۆتسپۆتی لاپتۆپ تا ٨ مۆبایل — بۆ پۆلی گەورە وای‌فای پۆل بەکاربهێنە)، پاشان کۆدەکەی سەر پرۆجێکتەر سکان دەکەن. پێویستی بە ئەپ نییە.",
        "quizStart" to "▶ دەستپێکردن",
        "quizAnswers" to "👥 %d وەڵام",
        "quizShowResults" to "📊 پیشاندانی ئەنجام",
        "quizCorrect" to "✓ ڕاست:",
        "quizNew" to "🔁 پرسیاری نوێ",
        "pickTitle" to "🎲 هەڵبژاردنی هەڕەمەکیی قوتابی",
        "pickNamesHint" to "ناوەکان، هەر ناوێک لە دێڕێکدا — یان بنووسە 1-30 بۆ ژمارە",
        "pickNoRepeat" to "هەمان قوتابی دووجار هەڵمەبژێرە (تا هەموو نۆرەیان دەگات)",
        "pickBtn" to "🎲 هەڵبژێرە",
        "pickAgain" to "🎲 دووبارە",
        "pickLists" to "📋 لیستی پۆلەکان",
        "pickNewList" to "➕ لیستی نوێ",
        "pickListName" to "ناوی لیست (بۆ نموونە قۆناغی ٢ – گرووپی A)",
        "pickDefaultList" to "پۆلەکەم",
        "pickEmpty" to "سەرەتا چەند ناوێک زیاد بکە.",
        "pickLeft" to "%d ماوە",
        "mutePhone" to "🔇 بێدەنگکردنی مۆبایل",
        "unmutePhone" to "🔈 دەنگی مۆبایل",
        "muteKillsPc" to "لەم مۆبایلەدا، بێدەنگکردن دەنگی نێردراو بۆ کۆمپیوتەریش بێدەنگ دەکات، بۆیە UOR-RC دەنگی مۆبایلەکەی گەڕاندەوە.\n\nئامۆژگاری: بۆ ڤیدیۆکانی گەلەری 🖼 وێنە و ڤیدیۆ بەکاربهێنە — تەنها لەسەر کۆمپیوتەر لێدەدرێن.",
        "scan" to "📷 سکان",
        "scanQr" to "📷 سکانکردنی QR لە UOR-RC لەسەر کۆمپیوتەر",
        "scanPrompt" to "کامێرا ڕووبکە ئەو QR ـەی لە UOR-RC لەسەر کۆمپیوتەرەکەیە",
        "scanBad" to "ئەمە QRی UOR-RC نییە. ئەوە سکان بکە کە لە UOR-RC لەسەر کۆمپیوتەرەکە دەردەکەوێت.",
        "joining" to "پەیوەستبوون بە %s…",
        "joinFailed" to "نەتوانرا پەیوەست بێت بە %s. لە ڕێکخستنەکانی وای‌فای مۆبایلەکە پەیوەستی بکە، پاشان UOR-RC خۆی پەیوەست دەبێت.",
        "cameraPerm" to "بۆ سکانکردنی QR کامێرا پێویستە.",
        "mute" to "🔇",
        "unmute" to "🔈",
        "mediaAgain" to "▶ گەڕانەوە بۆ هەمان وێنە و ڤیدیۆکان",
        "mediaNew" to "➕ هەڵبژاردنی نوێ",
        "media" to "🖼 وێنە و ڤیدیۆ",
        "mediaTitle" to "پیشاندان لەسەر پرۆجێکتەر",
        "mediaWhat" to "ئەمانە بە شاشەی تەواو لەسەر پرۆجێکتەر پیشان بدرێن، یان لەسەر کۆمپیوتەر پاشەکەوت بکرێن؟",
        "mediaShow" to "🖼 پیشاندان بە شاشەی تەواو",
        "mediaSave" to "💾 پاشەکەوت لەسەر کۆمپیوتەر",
        "mediaBt" to "ئەم فایلانە %d مێگابایتن. لە ڕێگەی بلوتوسەوە کات دەبات — وای‌فای زۆر خێراترە. بەردەوام بیت؟",
        "mediaPreparing" to "ئامادەکردن لەسەر پرۆجێکتەر… %d%%",
        "mediaClose" to "✕ داخستن",
        "mediaFill" to "⛶ پڕکردنەوە",
        "mediaRotate" to "🔄",
        "mediaPhoto" to "وێنە %d / %d",
        "mediaVideo" to "ڤیدیۆ %d / %d",
        "yes" to "بەڵێ",
        "files" to "📁 فایلەکان",
        "sendToPc" to "📤 ناردنی فایل بۆ کۆمپیوتەر",
        "whereFiles" to "فایلەکانی کۆمپیوتەر لە Downloads › UOR-RC پاشەکەوت دەکرێن.\nلەسەر کۆمپیوتەر: Downloads\\UOR-RC. هەروەها دەتوانیت لە هەر ئەپێکەوە Share → UOR-RC بکەیت، یان فایلەکان ڕابکێشیتە سەر پەنجەرەی UOR-RC لەسەر کۆمپیوتەر.",
        "sending" to "→ کۆمپیوتەر: %s  %d%%",
        "receiving" to "← کۆمپیوتەر: %s  %d%%",
        "received" to "لە کۆمپیوتەرەوە وەرگیرا: %s",
        "open" to "کردنەوە",
        "failedFile" to "گواستنەوە سەرکەوتوو نەبوو: %s",
        "sendLater" to "کاتێک کۆمپیوتەرەکە پەیوەست بوو دەنێردرێت.",
        "rotate" to "🔄 سووڕاندن %d°",
        "fill" to "⛶ پڕکردنەوەی شاشە",
        "fit" to "⛶ گونجاندن",
        "sound" to "🔊 دەنگ",
        "soundOff" to "🔇 دەنگ",
        "soundNeeds10" to "ناردنی دەنگ پێویستی بە ئەندرۆید ١٠ یان نوێترە.",
        "soundPerm" to "ئەندرۆید پێی دەڵێت \"تۆمارکردنی دەنگ\" — UOR-RC تەنها ئەوە دەبات کە ئەپەکان لێی دەدەن، نەک مایکرۆفۆن.",
        "phoneOnPc" to "📱 شاشەی مۆبایل لەسەر کۆمپیوتەر",
        "volSwap" to "بەرزکردنەوەی دەنگ = سلایدی دواتر (بە ئاسایی نزمکردنەوە = دواتر)",
        "leftBtn" to "کلیکی چەپ",
        "rightBtn" to "کلیکی ڕاست",
        "autoKb" to "کاتێک لەسەر کۆمپیوتەرەکە کلیک لە شوێنی نووسین دەکەم کیبۆرد بکەرەوە",
        "hideKb" to "⌄ شاردنەوە",
        "copy" to "کۆپی",
        "paste" to "پەیست",
        "undo" to "گەڕانەوە",
        "selAll" to "هەمووی دیاری بکە",
        "phoneHotspot" to "📱 هۆتسپۆت لەسەر ئەم مۆبایلە دروست بکە",
        "hsNeedPerm" to "ئەندرۆید ئەم ڕێگەپێدانەی پێویستە بۆ دروستکردنی هۆتسپۆت.",
        "hsOn" to "هۆتسپۆتی ئەم مۆبایلە هەڵکراوە",
        "hsInfo" to "ناو: %s\nوشەی نهێنی: %s",
        "hsAuto" to "UOR-RC لاپتۆپەکە بە شێوەی خۆکار پێوەی دەبەستێت (لە ڕێگەی بلوتوسەوە)… پاشان دەچێتە سەر وای‌فای.",
        "hsManual" to "لەسەر لاپتۆپەکە لیستی وای‌فای بکەرەوە و بەم تۆڕە پەیوەست ببە. UOR-RC خۆی پەیوەست دەبێت.",
        "hsOff" to "کوژاندنەوەی هۆتسپۆت",
        "hsFail" to "مۆبایلەکە نەیتوانی هۆتسپۆت دروست بکات (%s). ئەگەر هۆتسپۆتی ئاسایی هەڵکراوە، بیکوژێنەوە — یان لاپتۆپەکە بەوەوە ببەستە. لە ئەندرۆیدی کۆندا Location هەڵبکە.",
        "desktop" to "🖥 دێسکتۆپ",
        "backShow" to "▶ گەڕانەوە بۆ پاوەرپۆینت",
        "seeScreen" to "📺 بینینی شاشە",
        "hintMirror" to "ڕاستەوخۆ لەسەر ئەو شتە بدە کە دەتەوێت کلیکی لێ بکەیت · ڕاگرتن = کلیکی ڕاست · ڕاکێشان = ڕاکێشان · دوو پەنجە = زوومی وێنە",
        "viaBt" to "بلوتوس",
        "pinTitle" to "PINی وای‌فای",
        "pinMsg" to "ئەو PIN ـە ٤ ژمارەییە بنووسە کە لە UOR-RC لەسەر کۆمپیوتەرەکە دەردەکەوێت.",
        "pinFound" to "UOR-RC کۆمپیوتەری %s ی لە وای‌فایشدا دۆزییەوە. PIN ـەکەی بنووسە بۆ پەیوەندیی خێراتری وای‌فای.",
        "pinWrong" to "وای‌فای پەیوەست نەبوو. ئەو PIN ـە بپشکنە کە لە UOR-RC لەسەر کۆمپیوتەرەکە دەردەکەوێت.",
        "connMode" to "جۆری پەیوەندی",
        "modeAuto" to "خۆکار — سەرەتا وای‌فای، بلوتوس بۆ یەدەگ (پێشنیارکراو)",
        "modeWifi" to "تەنها وای‌فای",
        "modeBt" to "تەنها بلوتوس",
        "thisPhone" to "ناونیشانی ئەم مۆبایلە: %s",
        "searching" to "بەدوای کۆمپیوتەرەکەدا دەگەڕێت…",
        "btList" to "ئامێرەکانی بلوتوس…",
        "spotlight" to "🔦 تیشک",
        "zoom" to "🔍 زووم",
        "number" to "🔢 ژمارە",
        "text" to "📍 دەق",
        "size" to "قەبارە",
        "colorL" to "ڕەنگ",
        "write" to "✍️ نووسین",
        "writeHint" to "دەقێک بنووسە بۆ پیشاندان...",
        "confettiOn" to "🎊 کۆنفێتی: هەڵکراو",
        "confettiOff" to "🎊 کۆنفێتی: کوژاوە",
        "colored" to "🫟 ڕەنگاوڕەنگ",
        "reset" to "سفرکردنەوە",
        "pin" to "📍 دەرزی",
        "plain" to "💬 سادە",
        "box" to "🔲 چوارچێوە",
        "fontColor" to "ڕەنگی نووسین",
        "background" to "باکگراوند",
        "noBg" to "بێ باکگراوند",
        "addLabel" to "دانانی نیشانە",
        "editLabel" to "دەستکاریکردنی نیشانە",
        "labelHint" to "دەقەکەت لێرە بنووسە...",
        "save" to "پاشەکەوتکردن",
        "delete" to "سڕینەوە",
        "countdown" to "⌛ کاتی پێچەوانە",
        "stopwatch" to "⏱ کاتژمێری ڕاگرتن",
        "onProjector" to "لەسەر پرۆجێکتەر پیشانی بدە",
        "silent" to "بێدەنگ (بێ لەرینەوە)",
        "showPreviews" to "وێنۆچکەی سلایدەکان پیشان بدە",
        "hintSpot" to "دەست لێبدە و بیجووڵێنە — تیشکەکە بە دوای پەنجەتدا دێت · دوو پەنجە = زووم",
        "hintZoom" to "وەک وێنەکانی مۆبایل: بە دوو پەنجە زووم بکە · ڕاکێشان بۆ جووڵاندن · دوو جار لێدان بۆ زووم / گەڕانەوە",
        "hintNumber" to "لێبدە بۆ دانانی ژمارەی دواتر (کەمێک لە سەرووی پەنجەتەوە) · لە ژمارەیەک بدە بۆ لابردنی",
        "hintText" to "لەو شوێنەی نیشانەکەی لێ دەبێت بدە · لە نیشانەیەک بدە بۆ دەستکاری یان سڕینەوە"
    )

    fun t(key: String): String = (if (ku) ckb[key] else en[key]) ?: en[key] ?: key
    fun f(key: String, vararg args: Any): String = String.format(t(key), *args)
}
